### ISSUE TITLE
lockfile.h - add /lock an loldht runs without sudo

### ISSUE THREAD

**Issue by floriandd2ba** [technion/lol_dht22#16]
Hi,

please change lockfile.h:
#define LOCKFILE "/var/run/lock/dht.lock"

Because with this change, loldht can execute without root-permissions.
I thing, this directory has the permission for all users to write a file, not only root.
 

THX
Florian

**Comment by technion** [comment]
When I last visited this, wiringPi required root permissions to access the GPIO ports.

Has something changed here?

**Comment by floriandd2ba** [comment]
Hi, i think wiringpi use the suid flag. gpio works without sudo.
The gpio command is designed to be installed as a setuid program and called by a normal user without using the sudo command or logging in as root.
from 
http://wiringpi.com/the-gpio-utility/

**Comment by technion** [comment]
As you point out, the gpio command is setuid root so that it runs without sudo. This is consistent with my understanding that GPIO access requires root access.
Our code doesn't execute the gpio command, and similarly requires root access.

**Comment by jgtaylor** [comment]
root access is required to access /dev/kmem to directly toggle the
associated GPIO register(s).

**Comment by floriandd2ba** [comment]
In DHT22.c ist this flag
lock: 0 disables the lockfile (for running as non-root user)\n",argv[0]);

I think this a another workaround for non-Root use

This flag see i After Open this issue

**Comment by floriandd2ba** [comment]
And with this Chance loldht works for me without sudo now

**Comment by technion** [comment]
loldht calls wiringPi. As @jgtaylor points out, that call must be done as root.

There's certainly scope for privilege separation regarding the maths done outside the wiringPi calls, but that's out of scope of this issue.
