### ISSUE TITLE
More Stabel  readout on Buster Linux

### ISSUE THREAD

**Issue by Ravenbs** [technion/lol_dht22#17]
Here a few changes to get stable readouts also on Buster linux.
was very unstable after updating...

This change is important for retrys - because without this the retrys most likely fail:
Beginning of read_dht22_dat()
...
  pinMode(DHTPIN, OUTPUT);
  digitalWrite(DHTPIN, HIGH);
  delay(500);
  digitalWrite(DHTPIN, LOW);
  delay(10);		/
  digitalWrite(DHTPIN, HIGH);
  delayMicroseconds(5);
  pinMode(DHTPIN, INPUT);

Change the counter from 16 to 14 for a better 0/1 
      if (counter > 14)	
	      dht22_dat[j/8] |= 1;

and in main() function increase the delay to 3 seconds between retrys - the dht-22 need at least 2s to recover from broken communication.
And decrease the final wait time to 500ms - no need to spend such long time there.
  while (read_dht22_dat() == 0 && tries--) 
  {
     delay(3000); 
  }
  delay(500);
  if(lock)
    close_lockfile(lockfd);

And to fix a race condition that the state of a pin could change between the while loop and the line below it:
  uint8_t readInWhile = HIGH;
...
	// Warte auf Flanke... - initial High->low
    while ( (readInWhile = sizecvt(digitalRead(DHTPIN))) == laststate) {
      counter++;
      delayMicroseconds(2);
      if (counter == 255) {
        break;
      }
    }
	laststate = readInWhile;

Hope this helps, for me this is a stable connection again, over a very long wire (50m).

**Comment by technion** [comment]
Hi,

If you would like to supply a PR for this I'd be happy to review it.

**Comment by Ravenbs** [comment]
I attached the file here.
have no idea how to do a git PR ^^. sorry.

Also included the memory corruption fix if it reads more than 40 bits, what happen from time to time.

[dht22.c.txt](https://github.com/technion/lol_dht22/files/3977011/dht22.c.txt)

**Comment by technion** [comment]
I take memory corruptions very seriously but I don't feel arbitrarily increasing array sizes is an answer.

- i cannot be greater than 84, given: for ( i=0; i< 85; i++) 
- j is only incremented in this condition: if ((i >= 4) && (i%2 == 0))
- If you remove all wiringPi functions and let the loops run to the end, they terminate at j is 40 and i is 84
- dht22_dat is only written using dht22_dat[j/8] 

Given the above I cannot identify how it can "read more than 40 bits" into this array such that corruption occurs. If you 

The file you've provided has a lot of changes which makes it unsuitable for review as a memory corruption fix.

**Comment by Ravenbs** [comment]
Boundry check would be better, its quick and working ;).
I also see not how to get beyond 40, but my debug print showed a lot of times 41.

The array size was the only change again sthis, the rest is described in first post for a more stable communication.
