### ISSUE TITLE
The process will wait for good data forever

### ISSUE THREAD

**Issue by mronnlun** [technion/lol_dht22#6]
In dht22.c the code

    while (read_dht22_dat() == 0) 
    {
      delay(1000); // wait 1sec to refresh
    }

will keep the loop running forever if you get bad data. Maybe you could have a parameter that specifies the max number of iterations (which would roughly translate to seconds since there is a one second delay in the loop).

**Comment by technion** [comment]
Is this realistically a problem?
If you run this once per minute or whatever on a schedule, the locking mechanics will cause your new process to identify the old one is still running, and exit. The locking mechanic exists for this reason, and is less error prone (for example, a user could still set it to loop more than the amount of seconds until next execution).

**Comment by mronnlun** [comment]
The problem is that if there is some anomaly that causes bad data, e.g. a cable to the dht22 is loose, and you solve it by cutting the power from your device (e.g. Raspberry) the lock file will remain in place. 

That means that every cronjob would have to start with killing possible loldht processes and removing possible lock files. Maybe this needs to be done anyway even if the loldht process would have a timeout.

**Comment by shrx** [comment]
^This happened to me more than once.
