### ISSUE TITLE
Data not good, skip

### ISSUE THREAD

**Issue by speeskeek** [technion/lol_dht22#7]
Hi there,

I'm trying to debug my Pi (I'm building 3 zero's to be this:  http://www.instructables.com/id/Raspberry-Pi-Temperature-Humidity-Network-Monitor/) - but I ain't getting any results from the sensors.
I have 3 sensors (AM2302) lying around, and all the same (same store, same layout) - alle three no results ("Data not good, skip").
I had a raspberry zero running and working before with one of these sensors.

Where can I start to resolve this?
Is it a dependency?
is there a go low where it should high?
is there something missing in the /boot/config.txt ?

**Comment by shrx** [comment]
Do you have `WiringPi` installed?

**Comment by speeskeek** [comment]
i's in dutch, but the last phrase is the most important:
`pi@temperatuur1:/sys/bus/w1/devices/w1_bus_master1/00-800000000000 $ sudo apt-get install wiringpi
Pakketlijsten worden ingelezen... Klaar
Boom van vereisten wordt opgebouwd       
De statusinformatie wordt gelezen... Klaar
wiringpi is reeds de nieuwste versie.`


that is
`wiring is already the newest version`


I was trying now to manually read something, by going /sys/bus/1w/devices/... but can't find anything useful (w1_slave does not exist)

**Comment by woerty** [comment]
You can't manually read the DHTs in the OneWire fashion as they are not real w1 devices. If the sensors don't work for me it has always been a problem with the wiring of the DHTs to the Pi. Try the shortest cable length you have to avoid noise.

**Comment by technion** [comment]
Do you definitely have the correct pin configured?
I'm having a hard time coming up with something better than "works for me" without seeing your hardware.

**Comment by speeskeek** [comment]
@woerty : cable lenght is real short. Its the cable that came with it. About 5cm (2-3inch?).
@technion : yes definitely the right pin. I alse recompiled with another pin, and rewired it to test, but no luck.

What should be in config.txt? What dependency should I check? Or reinstall?

**Comment by woerty** [comment]
You do not have additional software installed? I had problems reading DHTs when I had CPU intensive software installed such as motion etc. For the reading the timing is crucial.

**Comment by speeskeek** [comment]
Not that I'm aware of, need to check cpu usage if there is something weird using cpu

**Comment by speeskeek** [comment]
hi there,

the process w1_bus_master1 is taking some CPU load (even when not trying to read).
the load is indeed to high... coused by ?
(it's a rip Zero doing nothing, except me running over ssh top )

> top - 07:40:03 up 6 min,  2 users,  load average: 0,28, 0,28, 0,16

**Comment by speeskeek** [comment]
reinstalled (same Rpi0) another distro (DietPi). same shit. 
but CPU load is better now.

**Comment by technion** [comment]
This is believed to be fixed in #9. Many thanks for your patience with this.
