### ISSUE TITLE
Data not good, skip

### ISSUE THREAD

**Issue by iamklaus** [technion/lol_dht22#9]
My DHT22 since a couple of days (I upgraded to Raspian Strech), my DHT22 is not working any more. It alwayz said "Data not good, skip".

I was recompiling your software, did not work. 

Then I modified dht22.c, line 81+82 to:

`if (1==1) { ....`

So, no matter how the data looks like, it will output the data. This is the output:

`pi@pimaster ~/dht22/lol_dht22 $ sudo ./loldht 
usage: ./loldht <pin> (<tries>)
description: pin is the wiringPi pin number
using 7 (GPIO 4)
Optional: tries is the number of times to try to obtain a read (default 100)Raspberry Pi wiringPi DHT22 reader
www.lolware.net
Humidity = 6553.50 % Temperature = -3276.70 *C `

I tried another DHT22, because I thought it was broken. Any suggestions?

**Comment by technion** [comment]
As per my advice on #10, i'm not sure what happened here. Is anyone aware of Raspbian Stretch changing anything?

There's obviously a wider issue but I'm at a loss regarding what it is.

**Comment by linuxonlinehelp** [comment]
seems the driver for gpio is buggy on stretch, on jessy same setup runs..
jessy kernel 4.9.28-v7+ ok
stretch kernel  4.9.56-v7+ only "data not good, skip"

**Comment by mrbashshell** [comment]
+1
I have the same problem. It works fine on Jessy with the first Raspy but not on Strech with my second one.

**Comment by Eurobertics** [comment]
+1
Same here, after serveral tries with different sensors and boards. Seems to work in Jessy, Stretch not.

**Comment by technion** [comment]
Just letting you know I'm aware of this.
I can write a lot of code- but I can't debug what seems to be a kernel issue. I'm continuing to investigate what may have broken this and how to code around it.

**Comment by technion** [comment]
Paulv has an update in my original forum thread, in which he describes a process to make it work on a modern kernel;

https://www.raspberrypi.org/forums/viewtopic.php?f=37&t=27215&start=75

Can anyone advise?

**Comment by timdonovanuk** [comment]
It works fine in Stretch for me (Pi Zero W) except I will always get a "Data not good, skip" first. But after that I get reliable reading. Looking how I can modify the code, because all the junk it outputs (including "Data not good, skip") is fairly useless for scraping into other scripts.

**Comment by mrbashshell** [comment]
I've tried it on Strech again with dtparam=spi=on but unfortunately it still does not work. I just get "Data not good, skip"

**Comment by planetar** [comment]
I see the same problem, raspberry 2 B, raspian (debian version 9.3)
./AdafruitDHT.py 22 4
Temp=25.1*  Humidity=41.3%

./loldht 7
Raspberry Pi wiringPi DHT22 reader
www.lolware.net
Data not good, skip
Data not good, skip

the sensor comes mounted on a small red board with 140C80 AM2302  DHT22 printed on the board and ASAIR on the white plastic case.
I got two of those sensors and both show the same results.

I tried the dtparam=spi=on but it didn't help any.
Same picture on a raspberry 3 B Rev. 1.2

**Comment by flowincircle** [comment]
For me, it helps to change the timings from 1 Microseconds to 2 Microseconds (dht22.c Line 61)

**Comment by technion** [comment]
Can anyone else replicate @flowincircle 's finding? If so, I will patch this.

**Comment by G15507** [comment]
Confirmed, using 2 microseconds during the read loop fixes the problem ...

**Comment by technion** [comment]
@G15507 Many thanks for this confirmation. I'll get a fix made.
